### ISSUE TITLE
jquery.textfill error

### ISSUE THREAD

**Issue by davidlday** [levifig/now-playing.widget#5]
I'm getting the following error message intermittently in Notifications and the Ubersicht debugger. Seems to show up when I first log in. I'm also getting some other redraw errors, so this might be a problem with Ubersicht. I just can't tell.

`/Users/dday/Library/Application Support/Übersicht/widgets/now-playing.widget/scripts/jquery.textfill.min.js: SyntaxError: Unexpected token (`

**Comment by davidlday** [comment]
Screenshot attached. Seems to happen even when removing the following from index.coffee:

```
      $.getScript('now-playing.widget/scripts/jquery.textfill.min.js', ->
        $('#now-playing').textfill
          minFontPixels: 8
          maxFontPixels: 16
          explicitHeight: 40
          innerTag: '#track'
```

But, if I remove that code _and_ the jquery.textfill.min.js file, then the messages stop. Everything appears to render just fine without the use of jquery.textfill. I still think the bug might be with Ubersicht, but you might consider eliminating it. I'm not going to do a pull request because I don't know why you included it originally, so I don't exactly know what to test for when taking it out. All I know is, it seems to work just fine for me without it on OSX 10.11.3 using Ubersicht 0.8 (30).

By the way, love the widget! Great work!

![screenshot 2016-03-02 04 17 26](https://cloud.githubusercontent.com/assets/1132144/13456041/0598181c-e02f-11e5-9b0e-88b75b73d3a4.png)

**Comment by levifig** [comment]
@davidlday Ya, the issue is with how Übersicht reads the file on its own, like it's a widget itself… :( I'm really hoping we can include JS/CS files without having Übersicht assume they're additional widgets! I might have to include it from a URL (it's a pretty small file)… Or include its code (not sure about licensing).

Thank you for the kind words! Glad you're enjoying it… :)

**Comment by davidlday** [comment]
Thanks for the explanation. Was afraid that might be the case. I'll just happily ignore the error for now!
