### ISSUE TITLE
JSON Parse Error: Unexpected EOF

### ISSUE THREAD

**Issue by butterthebuddha** [levifig/now-playing.widget#6]
From the debug console:

```
[now-playing-widget-now-playing-coffee] SyntaxError: JSON Parse error: Unexpected EOF
  in parse@[native code]()
```

Any idea what could be causing it? It fixes itself when I reload Übersicht but reappears after some time.

**Comment by levifig** [comment]
@awesomeaniruddh Übersicht is loading a script I'm including as an Übersicht script, which doesn't work. There is currently an open issue regarding this (felixhageloh/uebersicht#171), and a solution may be out soon… :) 

Thank you for reporting this.

**Comment by levifig** [comment]
Übersicht upcoming release does fix this issue. Beta is available here: https://github.com/felixhageloh/uebersicht/issues/171#issuecomment-219990353. :)

**Comment by levifig** [comment]
I'll keep it open until this new version is released in the stable branch… 👍

**Comment by levifig** [comment]
Latest version (0.9x) of Übersicht and this widget fixes this problem! 👍
