### ISSUE TITLE
Weird bottom bar

### ISSUE THREAD

**Issue by lub0s** [levifig/now-playing.widget#7]
I have this issue with your widget. Is this related to your widget only or am I missing something here ? http://imgur.com/a/6UIj9

**Comment by levifig** [comment]
That is odd! I'll definitely take a look at it… :) Thanks for reporting it!

**Comment by levifig** [comment]
@lupajz I still haven't been able to reproduce this… :(

**Comment by lub0s** [comment]
Oh sorry haven't noticed :) a tweaked your script now a bit and its gone so you can close it 👍

**Comment by theman480** [comment]
@lupajz  can you help me to remove this?

**Comment by lub0s** [comment]
@theman480 not sure how can I help you but you can take a look on my modified version https://gist.github.com/lupajz/19b176364947cf95c509cf1cd4211cd2

**Comment by levifig** [comment]
I'll test this myself and if it doesn't introduce other issues with folks who didn't experience this issue, I'll merge it in!

Thank you.

**Comment by theman480** [comment]
@lupajz  Thanks man!!

@levifig Thanks for the feedback.
