### ISSUE TITLE
Vox Player Integration

### ISSUE THREAD

**Issue by badummtss** [levifig/now-playing.widget#8]
hi,
can anyone please do a integration for vox player?
i had this in geektool before übersicht comes out.
Is there any chance to get vox player support like this one: http://support.coppertino.com/discussions/vox-for-ios/220-geektool-integration
thanks

**Comment by levifig** [comment]
That's a good idea! I'll definitely look into it… Thank you for the suggestion! :)

**Comment by badummtss** [comment]
No problem, i do what i can ;)

**Comment by levifig** [comment]
Coopertino doesn't seem interested in this, as seen by them closing every single ticket that requests this or something similar:
- http://support.coppertino.com/discussions/vox-for-ios/220-geektool-integration
- http://support.coppertino.com/discussions/vox-for-mac/4499-api
- http://support.coppertino.com/discussions/questions-suggestions/322-command-line-control-interface

If Vox does start providing an Applescript interface that includes song info AND art, feel free to reopen this and I'll reconsider. 👍
